// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPw5459inrWN7E9Kno7ffPr_vL9cLg3K8',
    appId: '1:665733485891:android:7aafdbfd16e8e4eb268bf6',
    messagingSenderId: '665733485891',
    projectId: 'reclaimify',
    storageBucket: 'reclaimify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_YQ3OgH9BSXSty9lZ7YF_8POam28J--E',
    appId: '1:665733485891:ios:f5c3d7a440cbe490268bf6',
    messagingSenderId: '665733485891',
    projectId: 'reclaimify',
    storageBucket: 'reclaimify.appspot.com',
    androidClientId: '665733485891-vamt1qaehrg178vrqjuhhmhn6a91137u.apps.googleusercontent.com',
    iosClientId: '665733485891-p8rblf5rdidg947fn25nup8gn8l2irv0.apps.googleusercontent.com',
    iosBundleId: 'io.yaksh.reclaimify',
  );
}
